### ISSUE TITLE
Purchase Invoice

### ISSUE THREAD

**Issue by SrinivasanTwilight** [odakerp2024/odakerp_finance_frontend#15]

**Comment by NewtonTwl** [comment]
Purchase Invoice 
1. Based on the Billing party and the Billing Office the TDS needs to calculated.
2. a) If the Billing party state (ie. Customer State from Customer in Accounting Place of supply) 
      and Billing Office state both are same it comes under the CGST & SGST.
   b) If both Customer state and the Office state are different means it comes under the IGST. (In this the whole % of tax need to covered)
Example:
a). If Customer State - Tamil Nadu & Office Office State - Tamil Nadu then the tax % Calculation comes under CGST & SGST
b). If Customer State - Tamil Nadu & Office Office State - Punjab then the tax % Calculation comes under IGST.
3. Calculation Part:
Tax Amount = Description Amount*Tax % paid
Total Amount = Description Amount + Tax Amount
4. CGST & SGST Calculation:
If the Billing party state & Customer State are same ( Whole sum of Total Tax Amount/2 ie: CGST & IGST amount)
Total Amount = Total Description Amount + CGST Amount + SGST Amount 
5. IGST Calculation:
If the Billing party state & Customer State are different ( Whole sum of Total Tax Amount single amount ie: IGST)
Total Amount = Total Description Amount + IGST Amount 
6. State condition will be checked by using the Office and Vendor Branch
7. RCM Yes/No condition
	a) If RCM is given Yes ---> The calculated  TDS_Tax and TDS_Amount needs to be shown
	b) If RCM is given No  ---> No TDS_Tax and TDS_Amount will be shown 
	c) If RCM is selected then calculation needs to be done,
	d) If RCM is unselected Just hide the GST Group% and no calculation done.
8. Change the Purchase Invoice Table structure:
	**Account, Rate, Quantity, Amount, Currency, Ex-Rate, GST Group%	Amount(CCR), TDS, RCM, Select**
9. Clarify the BL type with VASU.

**Comment by SrinivasanTwilight** [comment]
Started work on this
